---
- name: Upload backup script
  copy:
    src: backup
    dest: /librivox/bin/backup
    mode: 0755
  become: true

- name: Enable backup cronjob
  cron:
    name: backup
    minute: 15
    hour: 4
    job: /librivox/bin/backup
  become: true
