---
# Common stuff

- name: DocumentRoot
  file: path=/librivox/www/librivox.org state=directory recurse=true
  become: true

- name: mod_rewrite
  apache2_module: name=rewrite state=present
  become: true
  notify: Restart Apache

# Catalog stuff

- name: Create catalog database
  mysql_db: name=librivox_catalog state=present
  become: true
  notify:
    - Import catalog database

- name: Catalog database user
  mysql_user:
    name: catalog
    password: "{{ catalog_db_password }}"
    priv: librivox_catalog.*:ALL/librivox_forum.*:ALL
    host: localhost
    state: present
  become: true

- name: Git checkout
  git:
    repo: https://github.com/LibriVox/librivox-catalog.git
    dest: /librivox/www/librivox.org/catalog
    force: yes
  become: true

- name: Config files
  template:
    src: "{{ item }}.php"
    dest: "/librivox/www/librivox.org/catalog/application/config/{{ item }}.php"
  with_items:
    - config
    - database
    - iarchive_uploader
  become: true

- name: Symlinks
  # Needed by the catalog application, URLs are handled in the Apache config
  # file
  file:
    src: "/librivox/shared/{{ item.src }}"
    dest: "/librivox/www/librivox.org/catalog/public_html/{{ item.dest }}"
    state: link
  with_items:
    - { src: "librivox-validator-books", dest: "librivox-validator-books" }
    - { src: "uploads/uploads", dest: "uploads" }
  become: true

- name: PPA for mp3gain
  apt_repository:
    repo: ppa:flexiondotorg/audio
  become: true

- name: install mp3gain
  apt: name=mp3gain state=latest update_cache=yes
  become: true

# WordPress stuff

- name: Create blog database
  mysql_db: name=librivox_blog state=present
  become: true
  notify:
    - Import blog database

- name: WordPress database user
  mysql_user:
    name: librivox_blog
    password: "{{ blog_db_password }}"
    priv: librivox_blog.*:ALL
    host: localhost
    state: present
  become: true

- name: Download WordPress
  get_url:
    url: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"
    dest: /tmp/wordpress.tar.gz
    force: yes

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /librivox/www/librivox.org
    owner: root
    group: root
    copy: false
  become: true

- name: LibriVox theme from git
  git:
    repo: https://github.com/LibriVox/librivox-wordpress-theme.git
    dest: /librivox/www/librivox.org/wordpress/wp-content/themes/librivox
  become: true
 
- name: wp-config.php
  template:
    src: wp-config.php
    dest: /librivox/www/librivox.org/wordpress/wp-config.php
  become: true

- name: Install unzip
  apt: name=unzip state=latest
  become: true

- name: Download ACF
  get_url:
    url: "https://connect.advancedcustomfields.com/index.php?p=pro&a=download&k={{ acf_pro_key }}&t={{ acf_version }}"
    dest: /tmp/advanced-custom-fields.zip
    force: yes

- name: Install ACF
  unarchive:
    src: /tmp/advanced-custom-fields.zip
    dest: /librivox/www/librivox.org/wordpress/wp-content/plugins
    owner: root
    group: root
    copy: false
  become: true

- name: Download Jetpack
  get_url:
    url: "https://downloads.wordpress.org/plugin/jetpack.{{ jetpack_version }}.zip"
    dest: /tmp/jetpack.zip
    force: yes

- name: Install Jetpack
  unarchive:
    src: /tmp/jetpack.zip
    dest: /librivox/www/librivox.org/wordpress/wp-content/plugins
    owner: root
    group: root
    copy: false
  become: true

# Enable both as a single Apache site

- name: librivox.org config file
  template:
    src: librivox.org.conf
    dest: /etc/apache2/sites-available/librivox.org.conf
  become: true
  notify: Restart Apache

- name: Enable site
  file:
    src: /etc/apache2/sites-available/librivox.org.conf
    dest: /etc/apache2/sites-enabled/librivox.org.conf
    state: link
  become: true
  notify: Restart Apache
