---
# Common stuff

- name: DocumentRoot
  file:
    path: /librivox/www/librivox.org
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
  become: true

- name: mod_rewrite
  apache2_module:
    name: rewrite
    state: present
  become: true
  notify: Restart Apache

# Catalog stuff

- name: Create catalog database
  # We let the database be imported manually if necessary
  mysql_db:
    name: librivox_catalog
    state: present
  become: true

- name: Catalog database user
  mysql_user:
    name: catalog
    password: "{{ catalog_db_password }}"
    priv: librivox_catalog.*:ALL/librivox_forum.*:ALL
    host: localhost
    state: present
  become: true

- name: Git checkout
  git:
    repo: https://github.com/LibriVox/librivox-catalog.git
    dest: /librivox/www/librivox.org/catalog
    refspec: '{{ catalog_git_refspec }}'
    version: '{{ catalog_git_version }}'
    force: yes

- name: CodeIgniter sessions directory
  file:
    path: /tmp/php-sessions
    state: directory
    owner: www-data
    group: librivox
    mode: 0700
  become: true

- name: CodeIgniter sessions cleanup cronjob (daily)
  cron:
    name: CodeIgniter sessions cleanup (daily)
    special_time: daily
    job: 'find /tmp/php-sessions -atime +5 -delete'
  become: true

- name: CodeIgniter sessions cleanup cronjob (hourly)
  cron:
    name: CodeIgniter sessions cleanup (hourly)
    special_time: hourly
    job: 'find /tmp/php-sessions -size 0 -delete'
  become: true

- name: Config files
  template:
    src: "{{ item }}.php"
    dest: "/librivox/www/librivox.org/catalog/application/config/{{ item }}.php"
  with_items:
    - config
    - database
    - iarchive_uploader
    - email
  tags: passwords

- name: Symlinks
  # Needed by the catalog application, URLs are handled in the Apache config
  # file
  file:
    path: "/librivox/www/librivox.org/catalog/public_html/{{ item.dest }}"
    state: link
    src: "/librivox/shared/{{ item.src }}"
  with_items:
    - { src: "librivox-validator-books", dest: "librivox-validator-books" }
    - { src: "uploads/uploads", dest: "uploads" }

# WordPress stuff

- name: Create blog database
  # We let the database be imported manually if necessary
  mysql_db:
    name: librivox_blog
    state: present
  become: true

- name: WordPress database user
  mysql_user:
    name: librivox_blog
    password: "{{ blog_db_password }}"
    priv: librivox_blog.*:ALL
    host: localhost
    state: present
  become: true

- name: Extract WordPress
  unarchive:
    src: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"
    dest: /librivox/www/librivox.org
    remote_src: yes

- name: LibriVox theme from git
  git:
    repo: https://github.com/LibriVox/librivox-wordpress-theme.git
    dest: /librivox/www/librivox.org/wordpress/wp-content/themes/librivox
 
- name: wp-config.php
  template:
    src: wp-config.php
    dest: /librivox/www/librivox.org/wordpress/wp-config.php
  tags: passwords

- name: Install simple-cloudflare-turnstile
  unarchive:
    src: 'https://downloads.wordpress.org/plugin/simple-cloudflare-turnstile.{{ turnstile_version }}.zip'
    dest: /librivox/www/librivox.org/wordpress/wp-content/plugins
    remote_src: yes

# Enable both as a single Apache site

- name: librivox.org config file
  template:
    src: librivox.org.conf
    dest: /etc/apache2/sites-available/librivox.org.conf
  become: true
  notify: Restart Apache

- name: Enable site
  file:
    path: /etc/apache2/sites-enabled/librivox.org.conf
    state: link
    src: /etc/apache2/sites-available/librivox.org.conf
  become: true
  notify: Restart Apache
