---
- name: DocumentRoot
  file:
    path: /librivox/www/maintenance
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    recurse: true
  become: true

- name: Upload Apache config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "default.conf", dest: "/etc/apache2/sites-available" }
    - { src: "default-ssl.conf", dest: "/etc/apache2/sites-available" }
  become: true

- name: Upload index.html
  copy:
    src: index.html
    dest: /librivox/www/maintenance

# Sites are intentionally left disabled to allow for manual control.
