---
- name: DocumentRoot
  file: path=/librivox/www/maintenance state=directory recurse=true
  become: true

- name: Upload files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "index.html", dest: "/librivox/www/maintenance" }
    - { src: "000-default.conf", dest: "/etc/apache2/sites-available" }
    - { src: "default-ssl.conf", dest: "/etc/apache2/sites-available" }
  become: true

# Sites are intentionally left disabled to allow for manual control.
