---
- name: DocumentRoot
  file: path=/librivox/www/maintenance state=directory recurse=true

- name: Upload Apache config
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "000-default.conf", dest: "/etc/apache2/sites-available" }
    - { src: "default-ssl.conf", dest: "/etc/apache2/sites-available" }
  become: true

- name: Upload docroot
  copy:
    src: index.html
    dest: /librivox/www/maintenance

# Sites are intentionally left disabled to allow for manual control.
