---
- name: Install mediawiki dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - php5.6-mbstring
    - php5.6-xml
    - php5.6-intl
    - php5.6-apcu
    - imagemagick
    - memcached
  become: true

- name: Sphinx configuration file
  template:
    src: wiki.conf
    dest: /etc/sphinxsearch/wiki.conf
  become: true

- name: Database user
  mysql_user:
    name: mediawiki
    password: "{{ wiki_db_password }}"
    priv: librivox_mediawiki.*:ALL
    host: localhost
    state: present
  become: true

- name: Create database
  mysql_db: name=librivox_mediawiki state=present
  notify:
    - Import mediawiki database
  become: true

- name: Download mediawiki
  get_url:
    url: "https://releases.wikimedia.org/mediawiki/{{ mediawiki_ver_maj }}/mediawiki-{{ mediawiki_ver_min}}.tar.gz"
    dest: /tmp/mediawiki.tar.gz
    force: yes

- name: Extract mediawiki
  unarchive:
    src: /tmp/mediawiki.tar.gz
    dest: /librivox/www
    owner: root
    group: root
    copy: false
  become: true

- name: DocumentRoot
  file:
    src: "/librivox/www/mediawiki-{{ mediawiki_ver_min }}"
    dest: /librivox/www/wiki.librivox.org
    state: link
  become: true

- name: Local settings config file
  template:
    src: LocalSettings.php
    dest: /librivox/www/wiki.librivox.org/LocalSettings.php
  become: true

- name: Download sphinxsearch extension
  get_url:
    url: https://github.com/wikimedia/mediawiki-extensions-SphinxSearch/archive/master.tar.gz
    dest: /tmp/sphinxsearch-extension.tar.gz
    force: yes

- name: Extract sphinxsearch extension
  unarchive:
    src: /tmp/sphinxsearch-extension.tar.gz
    dest: /librivox/www/wiki.librivox.org/extensions
    owner: root
    group: root
    copy: false
  become: true

- name: Sphinxsearch extension symlink
  file:
    src: /librivox/www/wiki.librivox.org/extensions/mediawiki-extensions-SphinxSearch-master
    dest: /librivox/www/wiki.librivox.org/extensions/SphinxSearch
    state: link
  become: true

- name: sphinxsearch.api symlink
  file:
    src: /usr/share/sphinxsearch/api/sphinxapi.php
    dest: /librivox/www/wiki.librivox.org/extensions/SphinxSearch/sphinxapi.php
    state: link
  become: true

- name: Apache config file
  template:
    src: wiki.librivox.org.conf
    dest: /etc/apache2/sites-available/wiki.librivox.org.conf
  become: true
  notify: Restart Apache

- name: Enable site
  file:
    src: /etc/apache2/sites-available/wiki.librivox.org.conf
    dest: /etc/apache2/sites-enabled/wiki.librivox.org.conf
    state: link
  become: true
  notify: Restart Apache
