---
- name: Database user
  mysql_user:
    name: mediawiki
    password: "{{ wiki_db_password }}"
    priv: librivox_mediawiki.*:ALL
    host: localhost
    state: present
  become: true

- name: Create database
  mysql_db:
    name: librivox_mediawiki
    state: present
  become: true

- name: DocumentRoot
  file:
    path: /librivox/www/wiki.librivox.org
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
  become: true

- name: images
  file:
    path: /librivox/www/wiki.librivox.org/images
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: www-data
    mode: 0775
  become: true

- name: Extract MediaWiki
  unarchive:
    src: "https://releases.wikimedia.org/mediawiki/{{ mediawiki_ver_maj }}/mediawiki-{{ mediawiki_ver_min}}.tar.gz"
    dest: /librivox/www/wiki.librivox.org
    remote_src: true
    extra_opts: [--strip-components=1]

- name: Local settings config file
  template:
    src: LocalSettings.php
    dest: /librivox/www/wiki.librivox.org/LocalSettings.php

- name: Apache config file
  template:
    src: wiki.librivox.org.conf
    dest: /etc/apache2/sites-available/wiki.librivox.org.conf
  become: true
  notify: Restart Apache

- name: Enable site
  file:
    path: /etc/apache2/sites-enabled/wiki.librivox.org.conf
    state: link
    src: /etc/apache2/sites-available/wiki.librivox.org.conf
  become: true
  notify: Restart Apache
