---
- name: Install mediawiki dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - php5.6-mbstring
    - php5.6-xml
    - php5.6-intl
    - php5.6-apcu
    - imagemagick
    - memcached
  become: true

- name: Sphinx configuration file
  template:
    src: wiki.conf
    dest: /etc/sphinxsearch/wiki.conf
  become: true

- name: Database user
  mysql_user:
    name: mediawiki
    password: "{{ wiki_db_password }}"
    priv: librivox_mediawiki.*:ALL
    host: localhost
    state: present
  become: true

- name: Create database
  mysql_db: name=librivox_mediawiki state=present
  notify:
    - Import mediawiki database
  become: true

- name: DocumentRoot
  # The next task needs this, for some reason
  file:
    path: /librivox/www/wiki.librivox.org
    state: directory

- name: Extract MediaWiki
  unarchive:
    src: "https://releases.wikimedia.org/mediawiki/{{ mediawiki_ver_maj }}/mediawiki-{{ mediawiki_ver_min}}.tar.gz"
    dest: /librivox/www/wiki.librivox.org
    remote_src: true
    extra_opts: [--strip-components=1]

- name: Local settings config file
  template:
    src: LocalSettings.php
    dest: /librivox/www/wiki.librivox.org/LocalSettings.php

- name: SphinxSearch extension git checkout
  git:
    repo: https://github.com/wikimedia/mediawiki-extensions-SphinxSearch.git
    dest: /librivox/www/wiki.librivox.org/extensions/SphinxSearch
    force: yes

- name: sphinxsearch.api symlink
  file:
    src: /usr/share/sphinxsearch/api/sphinxapi.php
    dest: /librivox/www/wiki.librivox.org/extensions/SphinxSearch/sphinxapi.php
    state: link

- name: Apache config file
  template:
    src: wiki.librivox.org.conf
    dest: /etc/apache2/sites-available/wiki.librivox.org.conf
  become: true
  notify: Restart Apache

- name: Enable site
  file:
    src: /etc/apache2/sites-available/wiki.librivox.org.conf
    dest: /etc/apache2/sites-enabled/wiki.librivox.org.conf
    state: link
  become: true
  notify: Restart Apache
