---
- name: Install
  apt: name=apache2 state=latest

- name: Ports configuration
  template: src=ports.conf dest=/etc/apache2/ports.conf
  notify: Restart Apache

- name: Enable SSL module
  apache2_module: name=ssl state=present 
  notify: Restart Apache

- name: SSL cipher suite
  lineinfile:
    dest: /etc/apache2/mods-enabled/ssl.conf
    regexp: '^(\s*)SSLCipherSuite'
    line: '\1SSLCipherSuite HIGH'
    backrefs: yes
  notify: Restart Apache

- name: SSL protocol
  lineinfile:
    dest: /etc/apache2/mods-enabled/ssl.conf
    regexp: '^(\s*)SSLProtocol'
    line: '\1SSLProtocol all -SSLv2 -SSLv3'
    backrefs: yes
  notify: Restart Apache

- name: Allow /librivox/www configuration file
  copy:
    src: allow-librivox-www.conf
    dest: /etc/apache2/conf-available/allow-librivox-www.conf
  notify: Restart Apache

- name: Enable allow /librivox/www configuration
  file:
    src: /etc/apache2/conf-available/allow-librivox-www.conf
    dest: /etc/apache2/conf-enabled/allow-librivox-www.conf
    state: link
  notify: Restart Apache

- name: Enabled and started
  service: name=apache2 enabled=true state=started
