- hosts: server
  vars_files:
    - versions.yml
  roles:
    - blog+catalog
    - wiki
    - { role: forum, when: "'production' in inventory_file" }
    - { role: forum_new, when: "'production' not in inventory_file" }
    - { role: sftp_access, when: "'localdev' not in inventory_file" }
    - { role: hostsfile_entries, when: "'production' not in inventory_file" }
    - { role: mail, when: "'production' in inventory_file" }
    - { role: backups, when: "'production' in inventory_file" }
    - { role: maintenance, when: "'production' in inventory_file" }
  handlers:
    - include: handlers.yml
