- hosts: production
  vars_files:
    - vars/versions.yaml
    - vars/production.enc
  roles:
    - { 'role': 'common', 'tags': 'common' }
    - { 'role': 'ssh_port', 'tags': 'ssh_port' }
    - { 'role': 'blog+catalog', 'tags': 'blog+catalog' }
    - { 'role': 'acf_pro', 'tags': 'acf_pro' }
    - { 'role': 'wiki', 'tags': 'wiki' }
    - { 'role': 'forum', 'tags': 'forum' }
    - { 'role': 'backup', 'tags': 'backup' }
    - { 'role': 'sftp_access', 'tags': 'sftp_access' }
    - { 'role': 'maintenance', 'tags': 'maintenance' }
  handlers:
    - import_tasks: handlers.yaml

- hosts: staging
  vars_files:
    - vars/versions.yaml
    - vars/staging.enc
  roles:
    - { 'role': 'common', 'tags': 'common' }
    - { 'role': 'ssh_port', 'tags': 'ssh_port' }
    - { 'role': 'hosts_entry', 'tags': 'hosts_entry' }
    - { 'role': 'blog+catalog', 'tags': 'blog+catalog' }
    - { 'role': 'acf_pro', 'tags': 'acf_pro' }
    - { 'role': 'wiki', 'tags': 'wiki' }
    - { 'role': 'forum', 'tags': 'forum' }
    - { 'role': 'sftp_access', 'tags': 'sftp_access' }
    - { 'role': 'maintenance', 'tags': 'maintenance' }
  handlers:
    - import_tasks: handlers.yaml
