- hosts: localdev
  vars_files:
    - versions.yaml
    - localdev-vars.yaml
  roles:
    - { 'role': 'common', 'tags': 'common' }
    - { 'role': 'self-signed_cert', 'tags': 'self-signed_cert' }
    - { 'role': 'hosts_entry', 'tags': 'hosts_entry' }
    - { 'role': 'blog+catalog', 'tags': 'blog+catalog' }
    - { 'role': 'acf_free', 'tags': 'acf_free' }
    - { 'role': 'wiki', 'tags': 'wiki' }
    - { 'role': 'forum', 'tags': 'forum' }
  handlers:
    - import_tasks: handlers.yaml
