- hosts: localdev
  vars_files:
    - vars/versions.yaml
    - vars/localdev.yaml
  roles:
    - { 'role': 'common', 'tags': 'common' }
    - { 'role': 'self-signed_cert', 'tags': 'self-signed_cert' }
    - { 'role': 'hosts_entry', 'tags': 'hosts_entry' }
    - { 'role': 'blog+catalog', 'tags': 'blog+catalog' }
    - { 'role': 'catalog_unit_tests', 'tags': 'catalog_unit_tests' }
    - { 'role': 'acf_free', 'tags': 'acf_free' }
    - { 'role': 'wiki', 'tags': 'wiki' }
    - { 'role': 'forum', 'tags': 'forum' }
    - { 'role': 'db_import', 'tags': 'db_import' }
    - { 'role': 'restart_services', 'tags': 'restart_services' }
  handlers:
    - import_tasks: handlers.yaml
