---
- name: php-memcache
  apt: name=php5.6-memcache state=latest become=true

- name: Generate password
  local_action: command pwgen 32 1
  register: forum_db_password

- name: Create database
  mysql_db: name=librivox_forum state=present become=true
  notify:
    - Upload forum database
    - Import forum database

- name: Database user
  mysql_user:
    name: librivox_forum
    password: "{{ forum_db_password.stdout }}"
    priv: librivox_forum.*:ALL
    host: localhost
    state: present
    become: true

- name: Git checkout
  git:
    repo: https://github.com/LibriVox/librivox-phpbb.git
    dest: /librivox/www/forum.librivox.org
    force: yes

- name: mod_ssl
  apache2_module: name=ssl state=present
  notify: Restart Apache

- name: phpBB config file
  template:
    src: config.php
    dest: /librivox/www/forum.librivox.org/config.php

- name: Upload images.tar
  unarchive:
    src: images.tar
    dest: /librivox/www/forum.librivox.org

- name: Apache config file
  template:
    src: forum.librivox.org.conf
    dest: /etc/apache2/sites-available/forum.librivox.org.conf
    become: true
  notify: Restart Apache

- name: Enable site
  file:
    src: /etc/apache2/sites-available/forum.librivox.org.conf
    dest: /etc/apache2/sites-enabled/forum.librivox.org.conf
    state: link
    become: true
  notify: Restart Apache
