---
- name: Create database
  mysql_db:
    name: librivox_forum
    state: present
  become: true

- name: Database user
  mysql_user:
    name: librivox_forum
    password: "{{ forum_db_password }}"
    priv: librivox_forum.*:ALL
    host: localhost
    state: present
  become: true

- name: Git checkout
  git:
    repo: https://github.com/LibriVox/librivox-phpbb.git
    dest: /librivox/www/forum.librivox.org
    version: master
    force: yes

- name: phpBB dependencies
  command: php ../composer.phar install --no-dev --no-interaction
  args:
    chdir: /librivox/www/forum.librivox.org/phpBB

- name: phpBB config file
  template:
    src: config.php
    dest: /librivox/www/forum.librivox.org/phpBB/config.php

- name: cache directory Apache-writeable
  file:
    path: /librivox/www/forum.librivox.org/phpBB/cache
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: librivox
    mode: 0775
  become: true

- name: /librivox/sphinxsearch/data directory
  file:
    path: /librivox/sphinxsearch/data
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: sphinxsearch
    mode: 0775
  become: true

- name: Enable sphinx
  lineinfile:
    dest: /etc/default/sphinxsearch
    regexp: 'START=no'
    line: 'START=yes'
  become: true
  notify: Restart Sphinx

- name: Sphinx configuration file
  template:
    src: sphinx.conf
    dest: /etc/sphinxsearch/sphinx.conf
  become: true
  notify: Restart Sphinx

- name: Upload sphinx-index-update
  copy:
    src: sphinx-index-update
    dest: /librivox/bin/sphinx-index-update
    mode: 0755

- name: sphinx-index-update cronjob
  cron:
    name: sphinx-index-update
    minute: "*"
    job: /librivox/bin/sphinx-index-update
  # We need to be root to be able to SIGHUP sphinxsearch. The index files are
  # mode 0644, sphinxsearch can still read them even if thye're created by root.
  become: true

- name: Apache config file
  template:
    src: forum.librivox.org.conf
    dest: /etc/apache2/sites-available/forum.librivox.org.conf
  become: true
  notify: Restart Apache

- name: Enable site
  file:
    path: /etc/apache2/sites-enabled/forum.librivox.org.conf
    state: link
    src: /etc/apache2/sites-available/forum.librivox.org.conf
  become: true
  notify: Restart Apache
