---
- name: PHP extensions
  apt:
    name: ['php5.6-memcache', 'php5.6-mbstring']
    state: latest
  become: true

- name: Create database
  mysql_db: name=librivox_forum state=present
  notify:
    - Import forum database
  become: true

- name: Database user
  mysql_user:
    name: librivox_forum
    password: "{{ forum_db_password }}"
    priv: librivox_forum.*:ALL
    host: localhost
    state: present
  become: true

- name: Git checkout
  git:
    repo: https://github.com/LibriVox/librivox-phpbb.git
    dest: /librivox/www/forum.librivox.org
    version: master
    force: yes

- name: phpBB dependencies
  command: php ../composer.phar install --no-dev
  args:
    chdir: /librivox/www/forum.librivox.org/phpBB

- name: phpBB config file
  template:
    src: config.php
    dest: /librivox/www/forum.librivox.org/phpBB/config.php

- name: cache directory Apache-writeable
  file:
    path: /librivox/www/forum.librivox.org/phpBB/cache
    state: directory
    owner: www-data
    mode: 0755
  become: true

- name: Sphinx configuration file
  template:
    src: forum.conf
    dest: /etc/sphinxsearch/forum.conf
  become: true

- name: Apache config file
  template:
    src: forum.librivox.org.conf
    dest: /etc/apache2/sites-available/forum.librivox.org.conf
  become: true
  notify: Restart Apache

- name: Enable site
  file:
    src: /etc/apache2/sites-available/forum.librivox.org.conf
    dest: /etc/apache2/sites-enabled/forum.librivox.org.conf
    state: link
  become: true
  notify: Restart Apache
