---
- name: Users kara and jo
  user:
    name: '{{ item.username }}'
    password: "{{ item.password }}"
    shell: /bin/bash
    createhome: yes
    groups: librivox
  become: true
  with_items:
    - { username: kara, password: '{{ kara_password }}' }
    - { username: jo, password: '{{ jo_password }}' }

- name: User mc
  user:
    name: mc
    password: "{{ mc_password }}"
    shell: /usr/sbin/nologin
    home: /librivox/shared/uploads
    groups: librivox
  become: true

- name: sshd_config subsystem sftp
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^Subsystem sftp'
    line: 'Subsystem sftp internal-sftp'
  become: true

- name: sshd_config Match paras
  blockinfile:
    dest: /etc/ssh/sshd_config
    block: |
      Match User mc
          ChrootDirectory /librivox/shared/uploads
  become: true
