- name: Backups directories
  file:
    path: '{{ item }}'
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
  with_items:
    - /backups/database
    - /backups/user-content/wiki/images
    - /backups/user-content/wp-content/uploads
  become: true

- name: Upload backup
  template:
    src: backup
    dest: /librivox/bin/backup
    mode: 0755

- name: backup cronjob
  cron:
    name: backup
    minute: 15
    hour: 4
    job: /librivox/bin/backup
