---
- name: Generate DB password
  local_action: command pwgen 32 1
  register: mediawiki_db_password

- name: Ondrej's PPA
  apt_repository:
    repo: ppa:ondrej/php

- name: Install mediawiki dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - php5.6-mbstring
    - php5.6-xml
    - php5.6-intl
    - php5.6-apcu
    - imagemagick
    - memcached

- name: Install sphinx
  # The package in the Ubuntu repositories doesn't include sphinxsearch.api
  apt:
    deb: "http://sphinxsearch.com/files/sphinxsearch_{{ sphinx_version }}~xenial_amd64.deb"

- name: Sphinx configuration file
  template:
    src: sphinx.conf
    dest: /etc/sphinxsearch/sphinx.conf
  notify: Run indexer
  # In case the indexer has never run, we need to call it first to build
  # sphinx's database. The indexer task will then notify restart sphinx.

- name: Database user
  mysql_user:
    name: mediawiki
    password: "{{ mediawiki_db_password.stdout }}"
    priv: librivox_mediawiki.*:ALL
    host: localhost
    state: present

- name: Create database
  mysql_db: name=librivox_mediawiki state=present
  notify:
    - Upload mediawiki database
    - Import mediawiki database

- name: Download mediawiki
  get_url:
    url: "https://releases.wikimedia.org/mediawiki/{{ mediawiki_ver_maj }}/mediawiki-{{ mediawiki_ver_min}}.tar.gz"
    dest: /tmp/mediawiki.tar.gz

- name: Extract mediawiki
  unarchive:
    src: /tmp/mediawiki.tar.gz
    dest: /librivox/www
    copy: false
  notify: Update db schema
  # If the extract task changed something, it probably means a new mediawiki
  # version, so we should run the db schema update script.

- name: DocumentRoot
  file:
    src: /librivox/www/mediawiki-1.27.1
    dest: /librivox/www/wiki.librivox.org
    state: link

- name: Images
  unarchive:
    src: images.tar
    dest: /librivox/www/wiki.librivox.org

- name: Generate secret key
  local_action: command pwgen 64 1
  register: mediawiki_secret_key

- name: Local settings config file
  template:
    src: LocalSettings.php
    dest: /librivox/www/wiki.librivox.org/LocalSettings.php

- name: Download sphinxsearch extension
  get_url:
    url: https://github.com/wikimedia/mediawiki-extensions-SphinxSearch/archive/master.tar.gz
    dest: /tmp/sphinxsearch-extension.tar.gz

- name: Extract sphinxsearch extension
  unarchive:
    src: /tmp/sphinxsearch-extension.tar.gz
    dest: /librivox/www/wiki.librivox.org/extensions
    copy: false

- name: Sphinxsearch extension symlink
  file:
    src: /librivox/www/wiki.librivox.org/extensions/mediawiki-extensions-SphinxSearch-master
    dest: /librivox/www/wiki.librivox.org/extensions/SphinxSearch
    state: link

- name: sphinxsearch.api symlink
  file:
    src: /usr/share/sphinxsearch/api/sphinxapi.php
    dest: /librivox/www/wiki.librivox.org/extensions/SphinxSearch/sphinxapi.php
    state: link

- name: Apache config file
  template:
    src: wiki.librivox.org.conf
    dest: /etc/apache2/sites-available/wiki.librivox.org.conf
  notify: Restart Apache

- name: Enable site
  file:
    src: /etc/apache2/sites-available/wiki.librivox.org.conf
    dest: /etc/apache2/sites-enabled/wiki.librivox.org.conf
    state: link
  notify: Restart Apache
