---
- name: Upload forum database
  copy: src=librivox_forum.sql.bz2 dest=/tmp/librivox_forum.sql.bz2

- name: Import forum database
  mysql_db: name=librivox_forum state=import target=/tmp/librivox_forum.sql.bz2
