---
- name: Import mediawiki database
  mysql_db:
    name: librivox_mediawiki
    state: import
    target: /backup/latest/librivox_mediawiki.sql.bz2
    login_user: mediawiki
    login_password: "{{ wiki_db_password }}"
  async: 86400
