---
- name: Import catalog database
  mysql_db:
    name: librivox_catalog
    state: import
    target: /backups/latest/librivox_catalog.sql.bz2
    login_user: catalog
    login_password: "{{ catalog_db_password }}"
  async: 86400

- name: Import blog database
  mysql_db:
    name: librivox_blog
    state: import
    target: /backups/latest/librivox_blog.sql.bz2
    login_user: librivox_blog
    login_password: "{{ blog_db_password }}"
  async: 86400
