#!/bin/sh

d=/backups/`date +%F`
mkdir $d
for db in blog catalog mediawiki forum; do
    mysqldump librivox_$db | bzip2 -zc > $d/librivox_$db.sql.bz2
done
rm /backups/latest
ln -s $d /backups/latest

# We just keep a "rolling snapshot" of user content
rsync -a /librivox/www/wiki.librivox.org/images \
         /backups/user-content/wiki/
rsync -a /librivox/www/librivox.org/wordpress/wp-content/uploads \
         /backups/user-content/wp-content/
