#!/bin/sh

if [ `id -u` -eq 0 ]
then
    basedir="/etc/letsencrypt/live/librivox.org"
    fullchain="$basedir/fullchain.pem"
    privkey="$basedir/privkey.pem"
    if [ ! -f $fullchain -a ! -f $privkey ]
    then
        certbot certonly --webroot \
            -w /librivox/www/librivox.org/wordpress -d librivox.org \
            -w /librivox/www/forum.librivox.org/phpBB -d forum.librivox.org \
            -w /librivox/www/wiki.librivox.org -d wiki.librivox.org \
            -m notartom@gmail.com \
            --agree-tos \
            --no-eff-email
    fi
fi
