---
- name: Upload librivox-daily-cron
  copy:
    src: librivox-daily-cron
    dest: /usr/local/bin/librivox-daily-cron
    mode: 0755

- name: Librivox daily cron
  cron:
    name: librivox daily cron
    special_time: daily
    job: /usr/local/bin/librivox-daily-cron

- name: User kara
  user:
    name: kara
    password: "{{ kara_password }}"
    shell: /bin/bash
    createhome: yes

- name: User mc
  user:
    name: mc
    password: "{{ mc_password }}"
    shell: /usr/sbin/nologin
    home: /librivox/shared/uploads

- name: Users ruth and jo
  user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    shell: /usr/sbin/nologin
    home: /librivox/shared
  with_items:
    - { username: ruth, password: "{{ ruth_password }}" }
    - { username: jo, password: "{{ jo_password }}" }

- name: sshd_config subsystem sftp
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^Subsystem sftp'
    line: 'Subsystem sftp internal-sftp'

- name: sshd_config Match paras
  blockinfile:
    dest: /etc/ssh/sshd_config
    block: |
      Match User jo,ruth
          ChrootDirectory /librivox/shared
          ForceCommand internal-sftp
      Match User mc
          ChrootDirectory /librivox/shared/uploads
          ForceCommand internal-sftp
