---
- name: Install postfix
  apt: name=postfix state=latest update_cache=yes
  become: true

- name: main.cf config file
  copy: src=main.cf dest=/etc/postfix/main.cf
  become: true
  notify: restart postfix

