---
# Common stuff

- name: DocumentRoot
  file: path=/librivox/www/librivox.org state=directory recurse=true

- name: mod_rewrite
  apache2_module: name=rewrite state=present become=true
  notify: Restart Apache

# Catalog stuff

- name: Create catalog database
  mysql_db: name=librivox_catalog state=present become=true
  notify:
    - Upload catalog database
    - Import catalog database

- name: Generate catalog password
  local_action: command pwgen 32 1
  register: catalog_db_password

- name: Catalog database user
  mysql_user:
    name: catalog
    password: "{{ catalog_db_password.stdout }}"
    priv: librivox_catalog.*:ALL/librivox_forum.*:ALL
    host: localhost
    state: present
    become: true

- name: Git checkout
  git:
    repo: https://github.com/LibriVox/librivox-catalog.git
    dest: /librivox/www/librivox.org/catalog
    force: yes

- name: Config files
  template:
    src: "{{ item }}.php"
    dest: "/librivox/www/librivox.org/catalog/application/config/{{ item }}.php"
  with_items:
    - config
    - database
    - iarchive_uploader

- name: PPA for mp3gain
  apt_repository:
    repo: ppa:flexiondotorg/audio
    become: true

- name: install mp3gain
  apt: name=mp3gain state=latest update_cache=yes become=true

# WordPress stuff

- name: Create blog database
  mysql_db: name=librivox_blog state=present
  become: true
  notify:
    - Upload blog database
    - Import blog database

- name: Generate WordPress password
  local_action: command pwgen 32 1
  register: blog_db_password

- name: WordPress database user
  mysql_user:
    name: librivox_blog
    password: "{{ blog_db_password.stdout }}"
    priv: librivox_blog.*:ALL
    host: localhost
    state: present
    become: true

- name: Download WordPress
  get_url:
    url: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"
    dest: /tmp/wordpress.tar.gz
    force: yes

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /librivox/www/librivox.org
    copy: false

- name: LibriVox theme from git
  git:
    repo: https://github.com/LibriVox/librivox-wordpress-theme.git
    dest: /librivox/www/librivox.org/wordpress/wp-content/themes/librivox

- name: WP Salt
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
 
- name: wp-config.php
  template:
    src: wp-config.php
    dest: /librivox/www/librivox.org/wordpress/wp-config.php

- name: Install unzip
  apt: name=unzip state=latest become=true

- name: Download ACF
  get_url:
    url: "https://connect.advancedcustomfields.com/index.php?p=pro&a=download&k={{ acf_pro_key }}&t={{ acf_version }}"
    dest: /tmp/advanced-custom-fields.zip
    force: yes

- name: Install ACF
  unarchive:
    src: /tmp/advanced-custom-fields.zip
    dest: /librivox/www/librivox.org/wordpress/wp-content/plugins
    copy: false

- name: Download Jetpack
  get_url:
    url: "https://downloads.wordpress.org/plugin/jetpack.{{ jetpack_version }}.zip"
    dest: /tmp/jetpack.zip
    force: yes

- name: Install Jetpack
  unarchive:
    src: /tmp/jetpack.zip
    dest: /librivox/www/librivox.org/wordpress/wp-content/plugins
    copy: false

- name: Extract uploads.tar.bz2
  unarchive:
   src: uploads.tar.bz2
   dest: /librivox/www/librivox.org/wordpress/wp-content

# Enable both as a single Apache site

- name: librivox.org config file
  template:
    src: librivox.org.conf
    dest: /etc/apache2/sites-available/librivox.org.conf
    become: true
  notify: Restart Apache

- name: Enable site
  file:
    src: /etc/apache2/sites-available/librivox.org.conf
    dest: /etc/apache2/sites-enabled/librivox.org.conf
    state: link
    become: true
  notify: Restart Apache
