---
- name: Create database
  mysql_db: name=librivox_forum state=present
  notify:
    - Upload forum database
    - Import forum database

- name: Upload images.tar
  unarchive:
    src: images.tar
    dest: /librivox/www/forum.librivox.org
