---
# Install packages

- name: Install ca-certificates
  # This is needed to avoid SSL cert validation errors in the next task
  apt: name=ca-certificates state=latest update_cache=yes
  become: true

- name: PPAs
  apt_repository: repo={{ item }}
  with_items:
    - ppa:ondrej/php
      # For the fix to https://bz.apache.org/bugzilla/show_bug.cgi?id=53555
    - ppa:ondrej/apache2
    - ppa:certbot/certbot
  become: true

- name: Install packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - git
    - apache2
    - mariadb-server
    - python-mysqldb
    - php5.6-fpm
    - php5.6-mysql
    - php5.6-curl
    - python-certbot-apache
  become: true

# Cronjob

- name: bin directory
  file: path=/librivox/bin state=directory
  become: true

- name: Upload daily-cron
  copy:
    src: daily-cron
    dest: /librivox/bin/daily-cron
    mode: 0755
  become: true

- name: Enable daily cron
  cron:
    name: librivox daily cron
    minute: 45
    hour: 3
    job: /librivox/bin/daily-cron
  become: true

# Apache

- name: Ports configuration
  template: src=ports.conf dest=/etc/apache2/ports.conf
  become: true
  notify: Restart Apache

- name: MaxRequestWorkers line
  lineinfile:
    dest: /etc/apache2/mods-enabled/mpm_event.conf
    regexp: 'MaxRequestWorkers'
    line: "\tMaxRequestWorkers\t300"
  become: true
  notify: Restart Apache

- name: Apache modules
  apache2_module: name={{ item }} state=present
  with_items:
    - ssl
    - proxy_fcgi
  become: true
  notify: Restart Apache

- name: Disable access log
  file:
    name: /etc/apache2/conf-enabled/other-vhosts-access-log.conf
    state: absent
  become: true
  notify: Restart Apache

# MariaDB

- name: Configuration file
  template: src=librivox.cnf dest=/etc/mysql/mariadb.conf.d/99-librivox.cnf
  notify:
    - Stop MySQL
    - Remove ib_logfiles
    - Start MySQL
  become: true

# php-fpm

- name: Pool configuration file
  copy: src=www.conf.prod dest=/etc/php/5.6/fpm/pool.d/www.conf
  become: true
  notify: restart php-fpm
  when: "'production' in inventory_file"

- name: Pool configuration file
  copy: src=www.conf.dev dest=/etc/php/5.6/fpm/pool.d/www.conf
  become: true
  notify: restart php-fpm
  when: "'production' not in inventory_file"

# SphinxSearch

- name: Sphinx PPA
  apt_repository:
      repo: ppa:builds/sphinxsearch-rel22
  become: true

- name: Install sphinx
  apt: name=sphinxsearch state=latest update_cache=yes
  become: true

- name: Sphinx configuration files
  copy:
    src: "{{ item }}"
    dest: "/etc/sphinxsearch/{{ item }}"
  with_items:
    - common.conf
    - sphinx.conf
  become: true

- name: Upload sphinx-index-update
  copy:
    src: sphinx-index-update
    dest: /librivox/bin/sphinx-index-update
    mode: 0755
  become: true

- name: sphinx-index-update cronjob
  cron:
    name: sphinx-index-update
    minute: "*"
    job: /librivox/bin/sphinx-index-update
  become: true

# Shared directories

- name: librivox group
  group: name=librivox state=present
  become: true

- name: shared directory
  file: path=/librivox/shared/uploads state=directory recurse=yes
  become: true

- name: uploads and librivox-validator-books directories
  file:
    path: /librivox/shared/{{ item }}
    state: directory
    owner: www-data
    group: librivox
    mode: 0775
  with_items:
    - librivox-validator-books
    - uploads/uploads
  become: true

- name: Uploads robots.txt file
  copy:
    src: robots.txt
    dest: /librivox/shared/uploads/uploads/robots.txt
  become: true

# TLS
# We can't run certbot on anything other than production because DNS

- name: Upload certbot-issue script
  copy:
    src: certbot-issue
    dest: /librivox/bin/certbot-issue
    mode: 0755
  become: true
  when: "'production' in inventory_file"

- name: Run certbot-issue
  command: /librivox/bin/certbot-issue
  become: true
  when: "'production' in inventory_file"

- name: Renew cronjob
  cron:
    name: certbot renew
    special_time: monthly
    job: "/usr/bin/certbot renew --post-hook 'systemctl reload apache2'"
  become: true
  when: "'production' in inventory_file"

- name: Install python-openssl for self-signed cert
  apt: name=python-openssl state=latest update_cache=yes
  become: true
  when: "'localdev' in inventory_file"

- name: certs directory
  file: path=/etc/letsencrypt/live/librivox.org state=directory recurse=true
  become: true
  when: "'localdev' in inventory_file"

- name: localdev privkey
  openssl_privatekey:
    path: /etc/letsencrypt/live/librivox.org/privkey.pem
  become: true
  when: "'localdev' in inventory_file"

- name: localdev csr
  openssl_csr:
    privatekey_path: /etc/letsencrypt/live/librivox.org/privkey.pem
    path: /etc/letsencrypt/live/librivox.org/localdev.csr
    subject_alt_name: "DNS:librivox.org,DNS:forum.librivox.org,DNS:wiki.librivox.org"
  become: true
  when: "'localdev' in inventory_file"

- name: localdev self-signed cert
  openssl_certificate:
    path: /etc/letsencrypt/live/librivox.org/cert.pem
    privatekey_path: /etc/letsencrypt/live/librivox.org/privkey.pem
    csr_path: /etc/letsencrypt/live/librivox.org/localdev.csr
    provider: selfsigned
  become: true
  when: "'localdev' in inventory_file"

# Staging hosts file entry
- name: Staging hosts entry
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} librivox.org forum.librivox.org wiki.librivox.org"
  become: true
  when: "'production' not in inventory_file"

# Backups

- name: Upload backup script
  copy:
    src: backup
    dest: /librivox/bin/backup
    mode: 0755
  become: true
  when: "'production' in inventory_file"

- name: Enable backup cronjob
  cron:
    name: backup
    minute: 15
    hour: 4
    job: /librivox/bin/backup
  become: true
  when: "'production' in inventory_file"

# Google verification

- name: Verification file
  lineinfile:
    path: "/librivox/www/librivox.org/wordpress/{{ google_verification_filename }}"
    regexp: "google-site-verification"
    line: "{{ google_verification_contents }}"
    state: present
    create: yes
  when: "'production' in inventory_file"
