---
# Install packages

- name: Install packages
  apt:
    name: ['git', 'apache2', 'mariadb-server', 'php7.4-fpm', 'php7.4-mysql', 'php7.4-curl', 'python3-certbot-apache', 'sphinxsearch']
    state: latest
    update_cache: yes
  become: true

# Cronjob

- name: bin directory
  file: path=/librivox/bin state=directory
  become: true

- name: Upload daily-cron
  copy:
    src: daily-cron
    dest: /librivox/bin/daily-cron
    mode: 0755
  become: true

- name: Enable daily cron
  cron:
    name: librivox daily cron
    minute: '45'
    hour: '3'
    job: /librivox/bin/daily-cron
  become: true

# Apache

- name: Enable proxy_fcgi
  apache2_module:
    name: proxy_fcgi
    state: present
  become: true
  notify: Restart Apache

- name: Disable other-vhosts-access-log conf
  ansible.builtin.command:
    argv:
      - a2disconf
      - other-vhosts-access-log
  become: true
  notify: Restart Apache

- name: Enable php7.4-fpm conf
  ansible.builtin.command:
    argv:
      - a2enconf
      - php7.4-fpm
  become: true
  notify: Restart Apache

# PHP FPM

- name: Pool configuration file
  template: 
    src: www.conf
    dest: /etc/php/7.4/fpm/pool.d/www.conf
  become: true
  notify: Restart PHP FPM

# SphinxSearch

- name: Sphinx configuration files
  copy:
    src: "{{ item }}"
    dest: "/etc/sphinxsearch/{{ item }}"
  with_items:
    - common.conf
    - sphinx.conf
  become: true

- name: Upload sphinx-index-update
  copy:
    src: sphinx-index-update
    dest: /librivox/bin/sphinx-index-update
    mode: 0755
  become: true

- name: sphinx-index-update cronjob
  cron:
    name: sphinx-index-update
    minute: "*"
    job: /librivox/bin/sphinx-index-update
  become: true

# SSH port

- name: sshd_config port
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^Port '
    line: 'Port 58568'
  become: true

# Shared directories

- name: librivox group
  group:
    name: librivox
    state: present
  become: true

- name: shared directory
  file:
    path: /librivox/shared/uploads
    state: directory
    recurse: yes
  become: true

- name: uploads and librivox-validator-books directories
  file:
    path: /librivox/shared/{{ item }}
    state: directory
    owner: www-data
    group: librivox
    mode: 0775
  with_items:
    - librivox-validator-books
    - uploads/uploads
  become: true

- name: Uploads robots.txt file
  copy:
    src: robots.txt
    dest: /librivox/shared/uploads/uploads/robots.txt
  become: true

# TLS
# We can't run certbot on anything other than production because DNS

- name: Upload certbot-issue script
  copy:
    src: certbot-issue
    dest: /librivox/bin/certbot-issue
    mode: 0755
  become: true
  when: "'production' in inventory_file"

- name: Run certbot-issue
  command: /librivox/bin/certbot-issue
  become: true
  when: "'production' in inventory_file"

- name: Renew cronjob
  cron:
    name: certbot renew
    special_time: monthly
    job: "/usr/bin/certbot renew --post-hook 'systemctl restart apache2'"
  become: true
  when: "'production' in inventory_file"

- name: Install python3-openssl for self-signed cert
  apt:
    name: python3-openssl
    state: latest
    update_cache: yes
  become: true
  when: "'localdev' in inventory_file"

- name: certs directory
  file:
    path: /etc/letsencrypt/live/librivox.org
    state: directory
    recurse: true
  become: true
  when: "'localdev' in inventory_file"

- name: localdev privkey
  openssl_privatekey:
    path: /etc/letsencrypt/live/librivox.org/privkey.pem
  become: true
  when: "'localdev' in inventory_file"

- name: localdev csr
  openssl_csr:
    privatekey_path: /etc/letsencrypt/live/librivox.org/privkey.pem
    path: /etc/letsencrypt/live/librivox.org/localdev.csr
    subject_alt_name: "DNS:librivox.org,DNS:forum.librivox.org,DNS:wiki.librivox.org"
  become: true
  when: "'localdev' in inventory_file"

- name: localdev self-signed cert
  openssl_certificate:
    path: /etc/letsencrypt/live/librivox.org/cert.pem
    privatekey_path: /etc/letsencrypt/live/librivox.org/privkey.pem
    csr_path: /etc/letsencrypt/live/librivox.org/localdev.csr
    provider: selfsigned
  become: true
  when: "'localdev' in inventory_file"

# Staging hosts file entry
- name: Staging hosts entry
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} librivox.org forum.librivox.org wiki.librivox.org"
  become: true
  when: "'production' not in inventory_file"

# Backups

- name: Upload backup script
  copy:
    src: backup
    dest: /librivox/bin/backup
    mode: 0755
  become: true
  when: "'production' in inventory_file"

- name: Enable backup cronjob
  cron:
    name: backup
    minute: 15
    hour: 4
    job: /librivox/bin/backup
  become: true
  when: "'production' in inventory_file"

# Google verification

- name: Verification file
  lineinfile:
    path: "/librivox/www/librivox.org/wordpress/{{ google_verification_filename }}"
    regexp: "google-site-verification"
    line: "{{ google_verification_contents }}"
    state: present
    create: yes
  when: "'production' in inventory_file"
