---
- name: Import forum database
  mysql_db:
    name: librivox_forum
    state: import
    target: /backups/latest/librivox_forum.sql.bz2
    login_user: librivox_forum
    login_password: "{{ forum_db_password }}"
  async: 86400
