---
- name: Stop MySQL
  service: name=mysql state=stopped

- name: Remove ib_logfiles
  file: path=/var/lib/mysql/{{ item }} state=absent
  with_items:
    - ib_logfile0
    - ib_logfile1

- name: Start MySQL
  service: name=mysql state=started
