---
- name: Squid-ssl PPA
  apt_repository:
    repo: ppa:notartom/squid-ssl

- name: Install
  apt: name=squid state=latest update_cache=yes

- name: Default backend URLs
  copy:
    src: default_backend_urls.list
    dest: /etc/squid/default_backend_urls.list

- name: Configuration file
  template: src=squid.conf dest=/etc/squid/squid.conf
  notify: restart squid
