---
- name: Generate password
  local_action: command pwgen 32 1
  register: catalog_db_password

- name: Database user
  mysql_user:
    name: catalog
    password: "{{ catalog_db_password.stdout }}"
    priv: librivox_catalog.*:ALL/librivox_forum.*:ALL
    host: localhost
    state: present

- name: DocumentRoot
  file: path=/librivox/www/catalog.librivox.org state=directory recurse=true

- name: Git checkout
  git:
    repo: https://github.com/LibriVox/librivox-catalog.git
    dest: /librivox/www/catalog.librivox.org
    force: yes

- name: Config files
  template:
    src: "{{ item }}.php"
    dest: "/librivox/www/catalog.librivox.org/application/config/{{ item }}.php"
  with_items:
    - config
    - database
    - iarchive_uploader

- name: PPA for mp3gain
  apt_repository:
    repo: ppa:flexiondotorg/audio

- name: install mp3gain
  apt: name=mp3gain state=latest update_cache=yes

- name: mod_rewrite
  apache2_module: name=rewrite state=present
  notify: Restart Apache

- name: Catalog config file
  copy:
    src: catalog.conf
    dest: /etc/apache2/sites-available/catalog.conf
  notify: Restart Apache

- name: Enable site
  file:
    src: /etc/apache2/sites-available/catalog.conf
    dest: /etc/apache2/sites-enabled/catalog.conf
    state: link
  notify: Restart Apache

- name: mod_proxy_http
  apache2_module: name=proxy_http state=present

- name: librivox.org config file
  template:
    src: librivox.org.conf
    dest: /etc/apache2/sites-available/librivox.org.conf
  notify: Restart Apache

- name: Enable site
  file:
    src: /etc/apache2/sites-available/librivox.org.conf
    dest: /etc/apache2/sites-enabled/librivox.org.conf
    state: link
  notify: Restart Apache
