---
- name: Generate password
  local_action: command pwgen 32 1
  register: catalog_db_password

- name: Database user
  mysql_user:
    name: catalog
    password: "{{ catalog_db_password.stdout }}"
    priv: librivox_catalog.*:ALL/librivox_forum.*:ALL
    host: localhost
    state: present

- name: DocumentRoot
  file: path=/librivox/www/catalog.librivox.org state=directory recurse=true

- name: Git checkout
  git:
    repo: https://github.com/LibriVox/librivox-catalog.git
    dest: /librivox/www/catalog.librivox.org
    force: yes

- name: uploads symlinks
  file:
    src: /librivox/shared/uploads/uploads
    dest: /librivox/www/catalog.librivox.org/public_html/uploads
    state: link

- name: librivox-validator-books symlinks
  file:
    src: /librivox/shared/librivox-validator-books
    dest: /librivox/www/catalog.librivox.org/public_html/librivox-validator-books
    state: link

- name: CodeIgniter main config file
  template:
    src: config.php
    dest: /librivox/www/catalog.librivox.org/application/config/config.php

- name: Database config file
  template:
    src: database.php
    dest: /librivox/www/catalog.librivox.org/application/config/database.php

- name: Install mp3gain
  # mp3gain isn't available from the Xenial repos, download the Trusty .deb directly
  apt: deb=http://mirrors.kernel.org/ubuntu/pool/universe/m/mp3gain/mp3gain_1.5.2-r2-6_amd64.deb

- name: mod_rewrite
  apache2_module: name=rewrite state=present
  notify: Restart Apache

- name: Apache config file
  copy:
    src: catalog.librivox.org.conf
    dest: /etc/apache2/sites-available/catalog.librivox.org.conf
  notify: Restart Apache

- name: Enable site
  file:
    src: /etc/apache2/sites-available/catalog.librivox.org.conf
    dest: /etc/apache2/sites-enabled/catalog.librivox.org.conf
    state: link
  notify: Restart Apache

- name: Uploads Apache config file
  template:
    src: uploads.librivox.org.conf
    dest: /etc/apache2/sites-available/uploads.librivox.org.conf
  notify: Restart Apache

- name: Enable uploads
  file:
    src: /etc/apache2/sites-available/uploads.librivox.org.conf
    dest: /etc/apache2/sites-enabled/uploads.librivox.org.conf
    state: link
  notify: Restart Apache
