name: Deploy localdev
on:
  pull_request:
  workflow_dispatch:
jobs:
  deploy-localdev:
    uses: LibriVox/librivox-ansible/.github/workflows/localdev.yaml@master
    with:
      catalog_git_branch: master
      playbooks_repo: ${{ github.repository }}
      playbooks_repo_ref: ${{ github.ref }}
